---
- name: "Reload systemd"
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: not ansible_is_chroot

- name: "Restart NetworkManager"
  ansible.builtin.service:
    name: "NetworkManager"
    state: "restarted"
  when: not ansible_is_chroot
