---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "Configure archlinux network"
  ansible.builtin.include_tasks: configure-archlinux.yml
  when: ansible_os_family == "Archlinux"
