---
- name: "Reload systemd"
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: not ansible_is_chroot

- name: "Restart ssh"
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: "restarted"
  when: not ansible_is_chroot
