---
- name: Converge
  hosts: instance
  vars:
    username: test_user
  roles:
    - role: network
    - role: ssh
      vars:
        ssh_port: 1337
    - role: user
      vars:
        user_public_keys:
          - "ssh-rsa AAAAB3NzaC1yc2E...Q02P1Eamz/nT4I3"
